apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minikube-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my-minikubeapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minikube-app-service
                port:
                  number: 80
